classdef BBox2d < robotics.ros.Message
    %BBox2d MATLAB implementation of swarm_msgs/BBox2d
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'swarm_msgs/BBox2d' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '7d510f65225aa2666a98dd49847a5681' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsPoint32Class = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Point32') % Dispatch to MATLAB class for message type geometry_msgs/Point32
    end
    
    properties (Dependent)
        LeftBottom
        RightTop
    end
    
    properties (Access = protected)
        Cache = struct('LeftBottom', [], 'RightTop', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'LeftBottom', 'RightTop'} % List of non-constant message properties
        ROSPropertyList = {'left_bottom', 'right_top'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = BBox2d(msg)
            %BBox2d Construct the message object BBox2d
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function leftbottom = get.LeftBottom(obj)
            %get.LeftBottom Get the value for property LeftBottom
            if isempty(obj.Cache.LeftBottom)
                obj.Cache.LeftBottom = feval(obj.GeometryMsgsPoint32Class, obj.JavaMessage.getLeftBottom);
            end
            leftbottom = obj.Cache.LeftBottom;
        end
        
        function set.LeftBottom(obj, leftbottom)
            %set.LeftBottom Set the value for property LeftBottom
            validateattributes(leftbottom, {obj.GeometryMsgsPoint32Class}, {'nonempty', 'scalar'}, 'BBox2d', 'LeftBottom');
            
            obj.JavaMessage.setLeftBottom(leftbottom.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.LeftBottom)
                obj.Cache.LeftBottom.setJavaObject(leftbottom.getJavaObject);
            end
        end
        
        function righttop = get.RightTop(obj)
            %get.RightTop Get the value for property RightTop
            if isempty(obj.Cache.RightTop)
                obj.Cache.RightTop = feval(obj.GeometryMsgsPoint32Class, obj.JavaMessage.getRightTop);
            end
            righttop = obj.Cache.RightTop;
        end
        
        function set.RightTop(obj, righttop)
            %set.RightTop Set the value for property RightTop
            validateattributes(righttop, {obj.GeometryMsgsPoint32Class}, {'nonempty', 'scalar'}, 'BBox2d', 'RightTop');
            
            obj.JavaMessage.setRightTop(righttop.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.RightTop)
                obj.Cache.RightTop.setJavaObject(righttop.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.LeftBottom = [];
            obj.Cache.RightTop = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.LeftBottom = copy(obj.LeftBottom);
            cpObj.RightTop = copy(obj.RightTop);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.LeftBottom = feval([obj.GeometryMsgsPoint32Class '.loadobj'], strObj.LeftBottom);
            obj.RightTop = feval([obj.GeometryMsgsPoint32Class '.loadobj'], strObj.RightTop);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.LeftBottom = saveobj(obj.LeftBottom);
            strObj.RightTop = saveobj(obj.RightTop);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.swarm_msgs.BBox2d.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.swarm_msgs.BBox2d;
            obj.reload(strObj);
        end
    end
end
