classdef Detector < robotics.ros.Message
    %Detector MATLAB implementation of swarm_msgs/Detector
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'swarm_msgs/Detector' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'b56b7a27d92ac9f700fefe94d3641059' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        SwarmMsgsObjectClass = robotics.ros.msg.internal.MessageFactory.getClassForType('swarm_msgs/Object') % Dispatch to MATLAB class for message type swarm_msgs/Object
    end
    
    properties (Dependent)
        Objects
    end
    
    properties (Access = protected)
        Cache = struct('Objects', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Objects'} % List of non-constant message properties
        ROSPropertyList = {'objects'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Detector(msg)
            %Detector Construct the message object Detector
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function objects = get.Objects(obj)
            %get.Objects Get the value for property Objects
            if isempty(obj.Cache.Objects)
                javaArray = obj.JavaMessage.getObjects;
                array = obj.readJavaArray(javaArray, obj.SwarmMsgsObjectClass);
                obj.Cache.Objects = feval(obj.SwarmMsgsObjectClass, array);
            end
            objects = obj.Cache.Objects;
        end
        
        function set.Objects(obj, objects)
            %set.Objects Set the value for property Objects
            if ~isvector(objects) && isempty(objects)
                % Allow empty [] input
                objects = feval([obj.SwarmMsgsObjectClass '.empty'], 0, 1);
            end
            
            validateattributes(objects, {obj.SwarmMsgsObjectClass}, {'vector'}, 'Detector', 'Objects');
            
            javaArray = obj.JavaMessage.getObjects;
            array = obj.writeJavaArray(objects, javaArray, obj.SwarmMsgsObjectClass);
            obj.JavaMessage.setObjects(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Objects)
                obj.Cache.Objects = [];
                obj.Cache.Objects = obj.Objects;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Objects = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Objects = copy(obj.Objects);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            ObjectsCell = arrayfun(@(x) feval([obj.SwarmMsgsObjectClass '.loadobj'], x), strObj.Objects, 'UniformOutput', false);
            obj.Objects = vertcat(ObjectsCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Objects = arrayfun(@(x) saveobj(x), obj.Objects);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.swarm_msgs.Detector.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.swarm_msgs.Detector;
            obj.reload(strObj);
        end
    end
end
