classdef Flowpixel < robotics.ros.Message
    %Flowpixel MATLAB implementation of swarm_msgs/Flowpixel
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'swarm_msgs/Flowpixel' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '12f0fc35b70c280e837318087a2ec774' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsPoint32Class = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Point32') % Dispatch to MATLAB class for message type geometry_msgs/Point32
    end
    
    properties (Dependent)
        StartPoint
        Direction
    end
    
    properties (Access = protected)
        Cache = struct('StartPoint', [], 'Direction', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Direction', 'StartPoint'} % List of non-constant message properties
        ROSPropertyList = {'direction', 'start_point'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Flowpixel(msg)
            %Flowpixel Construct the message object Flowpixel
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function startpoint = get.StartPoint(obj)
            %get.StartPoint Get the value for property StartPoint
            if isempty(obj.Cache.StartPoint)
                obj.Cache.StartPoint = feval(obj.GeometryMsgsPoint32Class, obj.JavaMessage.getStartPoint);
            end
            startpoint = obj.Cache.StartPoint;
        end
        
        function set.StartPoint(obj, startpoint)
            %set.StartPoint Set the value for property StartPoint
            validateattributes(startpoint, {obj.GeometryMsgsPoint32Class}, {'nonempty', 'scalar'}, 'Flowpixel', 'StartPoint');
            
            obj.JavaMessage.setStartPoint(startpoint.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.StartPoint)
                obj.Cache.StartPoint.setJavaObject(startpoint.getJavaObject);
            end
        end
        
        function direction = get.Direction(obj)
            %get.Direction Get the value for property Direction
            if isempty(obj.Cache.Direction)
                obj.Cache.Direction = feval(obj.GeometryMsgsPoint32Class, obj.JavaMessage.getDirection);
            end
            direction = obj.Cache.Direction;
        end
        
        function set.Direction(obj, direction)
            %set.Direction Set the value for property Direction
            validateattributes(direction, {obj.GeometryMsgsPoint32Class}, {'nonempty', 'scalar'}, 'Flowpixel', 'Direction');
            
            obj.JavaMessage.setDirection(direction.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Direction)
                obj.Cache.Direction.setJavaObject(direction.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.StartPoint = [];
            obj.Cache.Direction = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.StartPoint = copy(obj.StartPoint);
            cpObj.Direction = copy(obj.Direction);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.StartPoint = feval([obj.GeometryMsgsPoint32Class '.loadobj'], strObj.StartPoint);
            obj.Direction = feval([obj.GeometryMsgsPoint32Class '.loadobj'], strObj.Direction);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.StartPoint = saveobj(obj.StartPoint);
            strObj.Direction = saveobj(obj.Direction);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.swarm_msgs.Flowpixel.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.swarm_msgs.Flowpixel;
            obj.reload(strObj);
        end
    end
end
