classdef Pipeline < robotics.ros.Message
    %Pipeline MATLAB implementation of swarm_msgs/Pipeline
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'swarm_msgs/Pipeline' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '84209a6c133d2fd4ce0456b10643d480' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        StdMsgsUInt32Class = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/UInt32') % Dispatch to MATLAB class for message type std_msgs/UInt32
        SwarmMsgsPipeunitClass = robotics.ros.msg.internal.MessageFactory.getClassForType('swarm_msgs/Pipeunit') % Dispatch to MATLAB class for message type swarm_msgs/Pipeunit
    end
    
    properties (Dependent)
        Pipetype
        Units
    end
    
    properties (Access = protected)
        Cache = struct('Pipetype', [], 'Units', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Pipetype', 'Units'} % List of non-constant message properties
        ROSPropertyList = {'pipetype', 'units'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Pipeline(msg)
            %Pipeline Construct the message object Pipeline
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function pipetype = get.Pipetype(obj)
            %get.Pipetype Get the value for property Pipetype
            if isempty(obj.Cache.Pipetype)
                obj.Cache.Pipetype = feval(obj.StdMsgsUInt32Class, obj.JavaMessage.getPipetype);
            end
            pipetype = obj.Cache.Pipetype;
        end
        
        function set.Pipetype(obj, pipetype)
            %set.Pipetype Set the value for property Pipetype
            validateattributes(pipetype, {obj.StdMsgsUInt32Class}, {'nonempty', 'scalar'}, 'Pipeline', 'Pipetype');
            
            obj.JavaMessage.setPipetype(pipetype.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Pipetype)
                obj.Cache.Pipetype.setJavaObject(pipetype.getJavaObject);
            end
        end
        
        function units = get.Units(obj)
            %get.Units Get the value for property Units
            if isempty(obj.Cache.Units)
                javaArray = obj.JavaMessage.getUnits;
                array = obj.readJavaArray(javaArray, obj.SwarmMsgsPipeunitClass);
                obj.Cache.Units = feval(obj.SwarmMsgsPipeunitClass, array);
            end
            units = obj.Cache.Units;
        end
        
        function set.Units(obj, units)
            %set.Units Set the value for property Units
            if ~isvector(units) && isempty(units)
                % Allow empty [] input
                units = feval([obj.SwarmMsgsPipeunitClass '.empty'], 0, 1);
            end
            
            validateattributes(units, {obj.SwarmMsgsPipeunitClass}, {'vector'}, 'Pipeline', 'Units');
            
            javaArray = obj.JavaMessage.getUnits;
            array = obj.writeJavaArray(units, javaArray, obj.SwarmMsgsPipeunitClass);
            obj.JavaMessage.setUnits(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Units)
                obj.Cache.Units = [];
                obj.Cache.Units = obj.Units;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Pipetype = [];
            obj.Cache.Units = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Pipetype = copy(obj.Pipetype);
            cpObj.Units = copy(obj.Units);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Pipetype = feval([obj.StdMsgsUInt32Class '.loadobj'], strObj.Pipetype);
            UnitsCell = arrayfun(@(x) feval([obj.SwarmMsgsPipeunitClass '.loadobj'], x), strObj.Units, 'UniformOutput', false);
            obj.Units = vertcat(UnitsCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Pipetype = saveobj(obj.Pipetype);
            strObj.Units = arrayfun(@(x) saveobj(x), obj.Units);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.swarm_msgs.Pipeline.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.swarm_msgs.Pipeline;
            obj.reload(strObj);
        end
    end
end
